source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'MSwizzle_Example' do
  pod 'MSwizzle', :path => '../'

  target 'MSwizzle_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'FBSnapshotTestCase'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.2'
            end
        end
    end
end
