use_frameworks!

platform :ios, '8.0'

target 'MSwizzle_Example' do
  pod 'MSwizzle', :path => '../'

  target 'MSwizzle_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
